version: '2.3'

services:
  hackergame:
    container_name: &name hackergame
    hostname: *name
    image: ghcr.io/ustclug/hackergame:latest
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.docker
    volumes:
      - ./conf/local_settings.py:/opt/hackergame/conf/local_settings.py:ro
      - ./conf/settings/docker.py:/opt/hackergame/conf/settings/docker.py:ro
      - /run/uwsgi/app/hackergame/:/run/uwsgi/app/hackergame/
      # 存储静态网页与题目文件
      - /var/opt/hackergame/:/var/opt/hackergame/
      # 数据库，需要在容器外配置好 postgresql 和 pgbouncer
      - /var/run/postgresql/:/var/run/postgresql/
    depends_on:
      - memcached
  memcached:
    container_name: memcached
    image: memcached
    restart: always
